# Matrizes em Julia

In [28]:
n,m = 5,5
A = zeros(m,n)

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

Um for dentro de um for:
- Similar ao Python
- Um for que "anda" para as linhas, e um for que "anda" para as colunas

In [30]:
for i in 1:m
    for j in 1:n
        A[i,j] = i + j
    end
end
A

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [17]:
m,n = 5,5
B = zeros(m,n)

Um for para as linhas e para as colunas simultâneamente, em cada índice (m e n):

In [31]:
for i in 1:m, j in 1:n
        B[i,j]=i+3j
end
B

5×5 Array{Float64,2}:
 4.0   7.0  10.0  13.0  16.0
 5.0   8.0  11.0  14.0  17.0
 6.0   9.0  12.0  15.0  18.0
 7.0  10.0  13.0  16.0  19.0
 8.0  11.0  14.0  17.0  20.0

Ou do jeito mais "Juliano"... (e menor...  😎 ):

Associa-se o nome da matriz à operação que será aplicada em cada elemento (em função dos índices de linha e coluna), e a "área de atuação" da operação, isto é, onde percorrerão os índices.

In [32]:
C = [3i + 6j for i in 1:m, j in 1:n]

5×5 Array{Int64,2}:
  9  15  21  27  33
 12  18  24  30  36
 15  21  27  33  39
 18  24  30  36  42
 21  27  33  39  45